name: Verify linting

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hooky:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - name: Get latest Hooky release tag
        id: get_tag
        run: |
          TAG=$(curl -sSf https://api.github.com/repos/brandonchinn178/hooky/releases/latest \
                | jq -r .tag_name)
          echo "Latest Hooky tag is $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      - name: Download Hooky binary
        id: download
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          ASSET="hooky-${TAG#v}-linux-x86_64"
          URL="https://github.com/brandonchinn178/hooky/releases/download/${TAG}/${ASSET}"
          echo "Downloading $URL"
          sudo curl -L -o /usr/bin/hooky "${URL}"
          sudo chmod +x /usr/bin/hooky
      - name: Verify dependency versions
        run: |
          hooky --version
          rustfmt --version
      - name: Execute hooks
        run: hooky run --all --format=verbose
